# @package _global_
defaults:
 - _self_
 - targets: aortic_stenosis 

num_classes: 4
weights:
live_loading: False
#delete_segmentation: False
#balanced_accuracy: False
eval_metric: acc
data_orig:
task: classification

private_dataset_root: /workspace/as_tom
tufts_dataset_root: /workspace/TMED/approved_users_only
tufts_csv_name: #TODO
private_image_loader: mat_loader
tufts_image_loader: png_loader
data_train_tabular: /workspace/finetuned_df.csv
# data_val_tabular: cardiac_features_val_imputed_noOH.csv

data_train_imaging: /workspace/as_tom_annotations-all.csv
# data_val_imaging: cardiac_sa_es_ed_mm_val.pt

#field_lengths_tabular: tabular_lengths.pt 

#labels_train
